= How to Use The Tad OS Build Scripts
Ted Moseley <tmoseley1106@gmail.com>

WARNING: These scripts could very easily destroy your host system if you are
running these scripts on a native GNU/Linux install. You have been warned.

== Introduction

Welcome to the guide on building Tad OS from source code, using the Tad OS
build scripts. These scripts are written in pure Bash shell script syntax
(and are frequently checked using
link:https://www.shellcheck.net/[ ShellCheck]
) and should run in any recent bash shell. They are also highly commented
so even newcomers to Bash can understand what is going on.

The scripts are inspired by the
link:http://www.linuxfromscratch.org/[ Linux from Scratch Systemd guides]
and build everything from source code. These scripts also automate Linux from
Scrath much more than your average build script, so they require very little
work, and you do not need much knowledge of GNU/Linux to use them.

== Building Tad OS

=== Downloading

First things first, you are going to want to clone the repo:

```
$ git clone https://github.com/KeepPositive/Tad-OS.git
$ cd Tad-OS/
```

Now, the easiest way to download the source code you need is to use the
``get_packages.sh`` script. This script automates the wget download AND the
sha256 checksum processes for each package required. It has an assortment of
arguments that can be passed to it, but for now we will just download all of
the sources needed for a full Tad-OS installation.

TIP: Commands starting with a "$" indicate that the command should be run by a
normal user, while commands starting with a "#" should be run by the root user.

```
$ bash get_packages.sh all
```

=== Editing 'build.cfg'

Before any building can occur, you need to edit the ``build.cfg`` file. This
is an extremely simple file which allows the user to set some major variables
within the build scripts. These are pre-commented, so you should be able to
find out what you need to change.

TIP: Wherever you see a command with words in [SQUARE BRACKETS], insert whatever
is set in you build.cfg

=== Toolchain

In order to build the toolchain (similar to chapter 6 in the LFS book) you are
going to use two build scripts: ``prepare_toolchain.sh`` and
``build_toolchain.sh``. These scripts use packages from the base group and
create a small GNU/Linux system (AKA a *toolchain*) to create a clean base
system. The ``build_toolchain.sh`` script may take some time depending on your
processor speed. Go get a glass of water or something.

```
# bash prepare_toolchain.sh
$ su - [DEFAULT_USER]
$ cd [LFS]
$ bash build_toolchain.sh
$ exit
```

=== Base

Now that is complete, it is time to change root into the toolchain and build
the base system. This will also take quite a bit of time.

```
# bash prepare_base.sh
$ bash build_base1.sh
$ bash build_base2.sh
$ bash build_base3.sh
```

=== Finishing Up

This is still yet to be decided.
