= Tad OS

The simple OS for people who care about computers and stuff

This is an actively developed Linux-based OS which can be built using Bash build
scripts. This repo holds the build scripts, sha256 hashes, etc. needed to build
your very own Tad OS.

== System Compatibility

Theoretically, this build system will work on any CPU that is supported by 
the GNU Compiler and the Linux kernel. In reality, support will have to be  
built in to the build scripts, and proper patches must be applied. But if you 
want to build Tad OS from source, and you are using a supported processor 
type. The below CPUs types have been tested so far:

* x86_64

For a full list of successfully tested hardware, check out the 
link:docs/COMPATIBILITY.adoc[compatibility list].

== Usage

To understand how to use the Tad OS build script, please check out the
link:docs/MANUAL.adoc[documentation].

Also, to learn more about GNU/Linux and other related topics, check out
link:http://keeppositive.github.io/Tad-Docs/[Tad Docs]
where any user can learn a lot about their operating system. 

== Contribution & Changes

If you are unhappy with the way something works, or if you think a comment 
is oddly worded, etc., don't fret. You can
mailto:tmoseley1106@gmail.com[shoot me an email]
or you can post an issue here on the Tad OS repo.
